### ISSUE TITLE
Send failed LimitExceeded

### ISSUE THREAD

**Issue by Avetris** [FakeByte/EpicOnlineTransport#17]
Hi,

I start using it for a 10 player multiplayer p2p game and I have found an error on the library about the package size that are send from server. I think the limit that supports Epic Online is 1170 bytes (I have not found in the documentation), but the max package size that is send is 1178. This is because although it is set the maximun package size to 1169, when the Packet class is converted to bytes, it uses the data (1169 bytes) + id (4 bytes) + fragment (4 bytes) + more fragments (1 byte), resulting in 1178 bytes (the sum can be shown in Packet class).

The solution should be to change the maximun size to 1159, having the next line in EosTransport class:

<code>
public int GetMaxSinglePacketSize(int channelId) => P2PInterface.MaxPacketSize - 10;
</code>

Thanks.

**Comment by FakeByte** [comment]
Fixed in version 1.5.0
