### ISSUE TITLE
Not Updated Return types with new version i believe? 

### ISSUE THREAD

**Issue by jhmauritz** [FakeByte/EpicOnlineTransport#18]
Im new at all things networking but it looks like this function is just having some issues with its return type from its overriden function. 
![image](https://user-images.githubusercontent.com/46462219/124690224-7cce6700-de9f-11eb-8997-a0a6372f3983.png)
![image](https://user-images.githubusercontent.com/46462219/124690247-848e0b80-de9f-11eb-8721-f83d8104e6ad.png)

**Comment by FakeByte** [comment]
Fixed in version 1.5.0
