### ISSUE TITLE
Object referance not set to an instance of  an object

### ISSUE THREAD

**Issue by jeffinter** [FakeByte/EpicOnlineTransport#31]
I keep getting this error

`NullReferenceException: Object reference not set to an instance of an object
EpicTransport.EOSSDKComponent.Tick () (at Assets/Mirror/Runtime/Transport/EpicOnlineTransport/EOSSDKComponent.cs:147)
EpicTransport.EosTransport.ServerEarlyUpdate () (at Assets/Mirror/Runtime/Transport/EpicOnlineTransport/EosTransport.cs:106)
Mirror.NetworkServer.NetworkEarlyUpdate () (at Assets/Mirror/Runtime/NetworkServer.cs:1717)
Mirror.NetworkLoop.NetworkEarlyUpdate () (at Assets/Mirror/Runtime/NetworkLoop.cs:193)`

**Comment by FakeByte** [comment]
I believe you have the EOSSDKComponent on the same object as the NetworkManager and you use the offline/online scene feature. This will destroy the network manager with the EOSSDKComponent and recreate it in the next scene while switching from the online to the offline scene.
Move the EOSSDKComponent to its own object that is in DDOL to prevent this.
