### ISSUE TITLE
No EOS Keys in create menu

### ISSUE THREAD

**Issue by wndalci** [FakeByte/EpicOnlineTransport#34]
I wanted to give this awesome package a go but when I imported there was no EPS key option on the create menu.

When I relaunched it had to enter safe mode, Keep in mind I only have this and Mirror installed.

I'm sure it's just a compatibility issue with my Unity / mirror version so I was wondering what mirror and Unity version the creator is using for their game. Thanks in advance!

**Comment by FakeByte** [comment]
> I wanted to give this awesome package a go but when I imported there was no EPS key option on the create menu.
> 
> When I relaunched it had to enter safe mode, Keep in mind I only have this and Mirror installed.
> 
> I'm sure it's just a compatibility issue with my Unity / mirror version so I was wondering what mirror and Unity version the creator is using for their game. Thanks in advance!

We are using Mirror LTS which is version 46. But the transport can also be made compatible with newers versions easily, in the methods that have compile errors just reorder the arguments as the order has changed.

**Comment by wndalci** [comment]
Thanks! I'll give it a try later

**Comment by TheScruffyKat** [comment]
Is this the correct version? https://github.com/vis2k/Mirror/releases/tag/v46.0.0

**Comment by wndalci** [comment]
I got it working now, Thank you for your help earlier and of course making the package!

Is it possible to authenticate without the epic games authentication window?I plan to make a VR game but platforms such as Quest 2 cannot open pages in game (That I am aware of).

Will "Persistent Auth" do the trick?

 And again, thanks so much for sharing this amazing package it's a dream come true really

**Comment by FakeByte** [comment]
> I got it working now, Thank you for your help earlier and of course making the package!
> 
> Is it possible to authenticate without the epic games authentication window?I plan to make a VR game but platforms such as Quest 2 cannot open pages in game (That I am aware of).
> 
> Will "Persistent Auth" do the trick?
> 
> And again, thanks so much for sharing this amazing package it's a dream come true really

Yes, in the EOSSDKComponent you can set the credential type. You could either do device id which requires no login or steam/oculus login depending for which platforms you develop.
