### ISSUE TITLE
Invalid parameter EOS_Connect_CreateUserOptions.ContinuanceToken reason: property must not be null

### ISSUE THREAD

**Issue by Scales3837** [FakeByte/EpicOnlineTransport#46]
I'm getting the error
Invalid parameter EOS_Connect_CreateUserOptions.ContinuanceToken reason: property must not be null whenever I finish authenticating using the Epic Account Auth Interface.

**Comment by TheTechWiz5305** [comment]
Hello! How did you fix this issue?

**Comment by Scales3837** [comment]
iirc, I fixed it by using persistentauth / deviceID
